### ISSUE TITLE
Review: NavBar.jsx and SendHearingNotice.jsx

### ISSUE THREAD

**Issue by alvinedrada** [hi-doe-tracker/hi-doe-tracker#103]
## Overview

The focus for this code review will be centered around the NavBar.jsx page and SendHearingNotice.jsx page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-04](https://github.com/hi-doe-tracker/hi-doe-tracker/tree/review-04)

## Files to review

* [NavBar.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/main/app/imports/ui/components/NavBar.jsx)
* [SendHearingNotice.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/main/app/imports/ui/pages/SendHearingNotice.jsx)

## Checklists

* [Architecture](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-architecture-checklist)
* [Design](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-design-checklist)
* [JS](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-js-checklist)
* [React](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-react-checklist)

## Due date

September 27

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by gailag** [comment]
**Navbar.jsx**
L16-18: Could maybe improve the variable names of menuStyle, menuStyle1, and menuStyle2

**SendHearingNotice.jsx:**
L63-108: Refractor the contents inside the <Container> component (i.e. reduce the # of rows and columns used)
L48 & 51: Keep the order of the variables consistent from lines 15-21

**Comment by gbaik00** [comment]
Navbar.jsx
L43: More roles will be added so rather than adding each individual role to the list that are allowed to see the notification bell, to simplify it so that all roles can see it.

SendHearingNotice.jsx
L83-85, 91-93: can be shortened to one line instead of three.

**Comment by ujjwalrg** [comment]
SendHearingNotice.jsx
L44: A comment can be used to describe what this component does

NavBar.jsx
L11: A comment can be used to describe what this component does
Do we need that many dropdowns as Nav.Items. Can we have one nested dropdown to reduce the number of items in the NavBar?

**Comment by tkansaki** [comment]
Navbar.jsx:
L34: remove reference to STUFF components

SendHearingNotics.jsx:
L9,44,51: remove reference to STUFF collection

**Comment by charlie-robison** [comment]
## NavBar.jsx
DE-05: L16, L17, L18: A comment could be used to describe what each of these different menu styles are used for.
## SendHearingNotice.jsx
DE-05: L44: A comment could be used to explain what the component is doing.

**Comment by alvinedrada** [comment]
NavBar.jsx
JS-01: Name constructs appropriately
L16, L17, L18

SendHearingNotice.jsx
L83, 84, 85 can be one line
L91, 92, 93 can be one line

**Comment by rfitzy21** [comment]
### **NavBar.jsx**
DE-06 L16-18: Comment to describe difference in menu styles or name variables more descriptively

### **SendHearingNotice.jsx**
DE-03 L83-85, L91-93: make Select tags into one line

**Comment by tanner-ky** [comment]
NavBar.jsx 
SendHearingNotice.jsx
- Add comments to make it easier to follow
