### ISSUE TITLE
Review: BaseProfileCollection.js & ViewHearings.jsx

### ISSUE THREAD

**Issue by gailag** [hi-doe-tracker/hi-doe-tracker#129]
## Overview

The focus for this code review will be centered around the BaseProfileCollection.js collection and ViewHearings.jsx page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-05](https://github.com/hi-doe-tracker/hi-doe-tracker/tree/review-05)

## Files to review

* [BaseProfileCollection.js](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/review-05/app/imports/api/user/BaseProfileCollection.js)
* [ViewHearings.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/review-05/app/imports/ui/pages/ViewHearings.jsx)

## Checklists

* [Architecture](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-architecture-checklist)
* [Design](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-design-checklist)
* [JS](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-js-checklist)
* [React](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-react-checklist)

## Due date

October 4

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by gailag** [comment]
**ViewHearings.jsx**
- L3-6, L11-25: eliminate commented out code. Move it to the archive/directory (utilities)

**BaseProfileCollection.js**
- L28: use appropriate return statement
- L132: modify statement so that it doesn't refer to Stuff

**Comment by ujjwalrg** [comment]
**BaseProfileCollection.jsx**
Line54: Uses lodash library function
Line 12: Class component is missing JSDoc comment


**ViewHearings.jsx**
Line 11-25, 3-6: clean up the comments

**Comment by rfitzy21** [comment]
### **BaseProfileCollection.js**
JS-05 L3: avoid using lodash functions when possible
DE-03 L132: remove reference to Stuff
DE-04 L23-24, L31-32, L40-45, L120-122: Eliminate large comment blocks


### **ViewHearings.jsx**
DE-04 L3-6, L11-25: Eliminate comments

**Comment by rfitzy21** [comment]
### **BaseProfileCollection.js**
JS-05 L3: avoid using lodash functions when possible
DE-03 L132: remove reference to Stuff
DE-04 L23-24, L31-32, L40-45, L120-122: Eliminate large comment blocks


### **ViewHearings.jsx**
DE-04 L3-6, L11-25: Eliminate comments

**Comment by charlie-robison** [comment]
## BaseProfileCollection.js
JS-05: L3, L53: A lodash function is used which can be replaced with an ES6 built in function.
## ViewHearing.jsx
DE-01: L35-L55, L56-L76, L77, L97: This are identical lines of code which can be reduced using the map function on some test data.
DE-04: L3-L6, L11-L25: There is a large comment block that can be removed.

**Comment by tanner-ky** [comment]
BaseProfileCollection.js
- Large comment blocks
ViewHearings.jsx
- Remove excess comments

**Comment by tkansaki** [comment]
BaseProfileCollection.js:

Line 3, 53: Steer away from lodash (underscore)

ViewHearings.jsx:

Clean up comments
remove references to Stuff

**Comment by gbaik00** [comment]
#ViewHearings.jsx
L3-6, 11-25: Get rid of commented code

#BaseProfileCollection.js
L3: No Iodash
Various blocks of comments can be shortened or taken out completely

**Comment by kerensaa** [comment]
BaseProfileCollection.js
Avoid lodash


ViewHearings.jsx
Clean up comments

**Comment by alvinedrada** [comment]
BaseProfileCollection.jsx
DE-03: Ensure comments are appropriate
L132: remove reference to Stuff

ViewHearings.jsx
DE-01: Refactor to reduce duplication
All card components
DE-04/05: Eliminate large code blocks, ensure comments are appropriate
L11-25
