### ISSUE TITLE
Research how many user roles the application needs

### ISSUE THREAD

**Issue by ujjwalrg** [hi-doe-tracker/hi-doe-tracker#24]
Please do work for this task in a branch called issue-9.

Research how many users the application needs and what privileges/functionality they should/shouldn't have.

**Comment by rfitzy21** [comment]
Link to Research Doc:

https://docs.google.com/document/d/1-d3Myfj9PcCJ-4ppz40-Pt5WxJFtH4Xs26ZJLgQaClM/edit?usp=sharing
