### ISSUE TITLE
Create a mockup of the Submit Testimony page

### ISSUE THREAD

**Issue by gbaik00** [hi-doe-tracker/hi-doe-tracker#38]
![submittestimony](https://user-images.githubusercontent.com/60208409/188032746-7948010f-32f2-4cf9-8367-b0834386c3d2.PNG) Please do work for this task in a branch called issue-22.

**Comment by rfitzy21** [comment]
![Image](https://user-images.githubusercontent.com/111934099/190285308-f666dd82-bc71-4615-aae5-a100f068e69b.png)
