### ISSUE TITLE
Research review and approval process of the testimony

### ISSUE THREAD

**Issue by tanner-ky** [hi-doe-tracker/hi-doe-tracker#5]
Please do all the work for this issue in branch "issue-5"
Research what the review and approval process is for testimonies (create a research doc).

This is a part of main objective 4: The App must have a review and approval workflow for the testimonies.

**Comment by rfitzy21** [comment]
https://docs.google.com/document/d/1uyXtC276FZ-iWMqHHYbofubrrRJIDB_KYJiCIHRe8WY/edit?usp=sharing

**Comment by gailag** [comment]
[https://www.capitol.hawaii.gov/docs/cg/CitizensGuide.pdf](url)
