### ISSUE TITLE
Review: ViewBills and ViewBill

### ISSUE THREAD

**Issue by alvinedrada** [hi-doe-tracker/hi-doe-tracker#51]
## Review Branch

[review-1](https://github.com/hi-doe-tracker/hi-doe-tracker/tree/review-01)

## Files to review

* [ViewBills.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/main/app/imports/ui/pages/ViewBills.jsx)
* [ViewBill.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/main/app/imports/ui/pages/ViewBill.jsx)

## Checklists

* [Architecture](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-architecture-checklist)
* [Design](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-design-checklist)
* [JS](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-js-checklist)
* [React](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-react-checklist)

## Due date

9/13/2022

## For more information

The review process is documented at: https://courses.ics.hawaii.edu/ics414f22/morea/review/reading-idpm-review.html

**Comment by kerensaa** [comment]
Viewbills.jsx
Add some comments?
TODO: Both of the mobile/non mobile views contain almost all of the same code. Is it possible to combine these more?
 
 
ViewBill.jsx
Many lines of code, maybe add some comments to separate the sections?

**Comment by gbaik00** [comment]
ViewBills.jsx, ViewBills.jsx

Refactor names to make it easier to identify which is which

**Comment by rfitzy21** [comment]
ViewBills.jsx

DE-01: Can refactor code to dynamically change css class of html using javascript variables instead of repeating code.

if (mobileView) {
  var bills-class = ‘mb-3’  
}  else {
 var bills-class = ‘flex-column’
}
return (
      <Tab.Container id={PAGE_IDS.VIEW_BILLS} defaultActiveKey="all-bills">
        <br />
        <Row>
          <Col sm="1" />
          <Col sm="2">
            <h2>Offices</h2>
            <Nav variant="pills" className=bills-class>
              {officeNames.map(office => <Nav.Item><Nav.Link eventKey={office.eventKey}>{office.name}</Nav.Link></Nav.Item>)}
            </Nav>
            <br />
          </Col>
          <Col sm="8">
            <Tab.Content>
              {officeNames.map(officeName => <BillViewTab key={officeName.name} eventKey={officeName.eventKey} officeName={officeName.name} />)}
            </Tab.Content>
          </Col>
        </Row>
      </Tab.Container>
    );


ViewBill.jsx
DE-01: Create iterative to reduce amount of repeated code

**Comment by tkansaki** [comment]
ViewBills.jsx
refactor components for readability.

ViewBill.jsx
for repeated segments, use map on an array to make it more readable

**Comment by tanner-ky** [comment]
ViewBill.jsx, ViewBills.jsx
- File names very are similar
- Add comments giving brief description of files
