### ISSUE TITLE
Review: SubmitTestimony and MiniCalendar

### ISSUE THREAD

**Issue by rfitzy21** [hi-doe-tracker/hi-doe-tracker#93]
## Overview

The focus for this code review will be centered around the SubmitTestimony page and the MiniCalendar from the home page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

[review-03](https://github.com/hi-doe-tracker/hi-doe-tracker/tree/review-03)

## Files to review

* [SubmitTestimony.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/main/app/imports/ui/pages/SubmitTestimony.jsx)
* [MiniCalendar.jsx](https://github.com/hi-doe-tracker/hi-doe-tracker/blob/main/app/imports/ui/components/MiniCalendar.jsx)

## Checklists

* [Architecture](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-architecture-checklist)
* [Design](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-design-checklist)
* [JS](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-js-checklist)
* [React](https://courses.ics.hawaii.edu/ics414f22/morea/review/checklists/reading-react-checklist)

## Due date

Tuesday September 20th, 2022 1:30pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by charlie-robison** [comment]
## SubmitTestimony.jsx
L49, L52: DE-07: It may be repetitive to rewrite all of the data fields from line 49 to 52. Maybe refactoring can be done to reduce this repetition?
L9: RE-03: The imported collection is not the same name as the file.

## MiniCalender.jsx
L58, L161: DE-05: A comment can be used to describe what this function does.
L83-99: DE-02: There are deeply nested conditional statements in this area. Maybe there is a way to eliminate this while keeping the functionality?
L221-227: DE-01: These lines are very similar and can be refactored to eliminate duplication. Maybe mapping through days of the week array?

**Comment by gbaik00** [comment]
MiniCalendar.jsx
Shorten time zone in test data to HST (or none since this is only used in Hawaii)
Differentiate Sunday and Saturday, lines 221, 227.

SubmitTestimony.jsx
Lines 49 & 52 are maybe redundant? Same except for owner, is it possible to combine it somehow?
Lines 68-70 can be condensed into one line

**Comment by alvinedrada** [comment]
SubmitTestimony.jsx
Code is uniform and easy to read

MiniCalendar.jsx
DE-05: Ensure comments are appropriate
L46 Add comment to what this component does
DE-02: Avoid deeply nested conditionals
L78-102: Nested if/elses

**Comment by rfitzy21** [comment]
### **SubmitTestimony.jsx**
Lines 68-70 DE-03: can be one line instead of split into 3

### **MiniCalendar.jsx**
DE-02: Avoid deeply nested conditional statements in getDays function

**Comment by gailag** [comment]
MiniCalendar.jsx:
L78 - 99: deeply nested if/else blocks

SubmitTestimony.jsx
No comments, I personally think it's clean

**Comment by kerensaa** [comment]
SubmitTestimony.jsx
	Can´t find anything to change


MiniCalendar.jsx
	Line 51: Not a hundred percent sure what the variable isEventArray is
DE-02: Line 80-99: deeply nested if/else statements, is it possible to use a ternary operator?

**Comment by tanner-ky** [comment]
SubmitTestimony.jsx

MiniCalendar.jsx
- Deeply nested conditionals

**Comment by tkansaki** [comment]
MiniCalendar.jsx: 
-comments
-nested conditional

SubmitTestimony.jsx
-all good bro

**Comment by ujjwalrg** [comment]
SubmitTestimony.jsx
Line 52 could use object destructuring so we don't need line 49

MiniCalender.jsx
-nested conditional
